# 科学计算工具numpy

In [101]:
import numpy as np
import time

## 定义一维数组

In [4]:
data = np.arange(12)

In [5]:
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
list_data = list(range(12))

In [7]:
list_data

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

## 定义二维数组

In [32]:
data = np.array([[1, 2, 3, 4], [2, 3, 4, 5], [3, 4, 5, 6]])

In [12]:
data

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

## 查看数组维度

In [13]:
data.shape

(3, 4)

In [14]:
data.ndim

2

## 修改数组的维度

In [17]:
data = data.reshape(-1) # 将二维转为一维

In [18]:
data

array([1, 2, 3, 4, 2, 3, 4, 5, 3, 4, 5, 6])

In [20]:
data.reshape((3,4)) # 修改数据的维度，输入的参数要用元组

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

In [24]:
data.reshape((2,2,3))

array([[[1, 2, 3],
        [4, 2, 3]],

       [[4, 5, 3],
        [4, 5, 6]]])

## 查看数组的数据类型

In [25]:
data.dtype

dtype('int32')

In [34]:
data = data.astype('float32')

In [35]:
data.dtype

dtype('float32')

In [36]:
data

array([[1., 2., 3., 4.],
       [2., 3., 4., 5.],
       [3., 4., 5., 6.]], dtype=float32)

## 数据类型转换

In [37]:
data = data.astype('int32')

In [38]:
data

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

In [39]:
data/2

array([[0.5, 1. , 1.5, 2. ],
       [1. , 1.5, 2. , 2.5],
       [1.5, 2. , 2.5, 3. ]])

In [41]:
(data/2).dtype

dtype('float64')

## 定义特殊数组

In [56]:
data = np.zeros((3, 4)) # 定义一个全零的二维数组

In [45]:
data

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [50]:
data = np.ones((3, 4)) # 定义一个全一的数组

In [51]:
data

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [57]:
data = np.empty((3, 4))  # 定义一个空数组，空数组的值不确定

In [58]:
data

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [59]:
data = np.arange(1, 20, 2) # 定义个等差数列数组

In [60]:
data

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [63]:
data = np.arange(1, 20, 2).reshape((2,5)).astype('float32')

In [64]:
data

array([[ 1.,  3.,  5.,  7.,  9.],
       [11., 13., 15., 17., 19.]], dtype=float32)

In [65]:
data = np.ones((3, 4), dtype='float32') # 定义数组的时候声明数据类型

In [66]:
data

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

# numpy切片和索引

## 一维数组切片

In [68]:
data = np.arange(1, 20, 2)

In [69]:
data

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [71]:
data[5] # 通过索引（指针）获取数组元素

11

In [72]:
data[1:5]

array([3, 5, 7, 9])

In [73]:
data[1:9:2]

array([ 3,  7, 11, 15])

## 二维数组切片

In [74]:
data = np.arange(1, 20, 2).reshape((2,5))

In [77]:
data

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [82]:
data[1, 2], data[0, 0], data[1]

(15, 1, array([11, 13, 15, 17, 19]))

In [84]:
data[:,2] # 取第三列的数

array([ 5, 15])

In [88]:
data = np.arange(0, 16).reshape((4, 4))

In [89]:
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [91]:
data[1:3, 1:3]

array([[ 5,  6],
       [ 9, 10]])

## 数组的索引

In [92]:
data = np.empty((4, 4))

In [93]:
data

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.16821131e-307],
       [8.34441742e-308, 1.78022342e-306, 6.23058028e-307,
        9.79107872e-307],
       [6.89807188e-307, 7.56594375e-307, 6.23060065e-307,
        1.78021527e-306],
       [8.34454050e-308, 1.11261027e-306, 1.15706896e-306,
        1.33512173e-306]])

In [95]:
for i in range(4):
    data[i] = np.arange(i, i+4)

In [96]:
data

array([[0., 1., 2., 3.],
       [1., 2., 3., 4.],
       [2., 3., 4., 5.],
       [3., 4., 5., 6.]])

In [97]:
for i in data:
    print(i)

[0. 1. 2. 3.]
[1. 2. 3. 4.]
[2. 3. 4. 5.]
[3. 4. 5. 6.]


In [109]:
for i in data:
    for j in i:
        print(j)
#         time.sleep(1)

0.0
1.0
2.0
3.0
1.0
2.0
3.0
4.0
2.0
3.0
4.0
5.0
3.0
4.0
5.0
6.0


In [108]:
for i in range(4):
    for j in range(4):
        print(f'输出第{i}行，第{j}列的数为{data[i,j]}')
#         print('输出第{}行，第{}列的数'.format(i, j))

输出第0行，第0列的数为0.0
输出第0行，第1列的数为1.0
输出第0行，第2列的数为2.0
输出第0行，第3列的数为3.0
输出第1行，第0列的数为1.0
输出第1行，第1列的数为2.0
输出第1行，第2列的数为3.0
输出第1行，第3列的数为4.0
输出第2行，第0列的数为2.0
输出第2行，第1列的数为3.0
输出第2行，第2列的数为4.0
输出第2行，第3列的数为5.0
输出第3行，第0列的数为3.0
输出第3行，第1列的数为4.0
输出第3行，第2列的数为5.0
输出第3行，第3列的数为6.0


## 布尔索引

In [116]:
data = np.array(['赵大', '钱二', '张三', '李四', '王五'])

In [117]:
data

array(['赵大', '钱二', '张三', '李四', '王五'], dtype='<U2')

In [118]:
score = np.array([[60, 70, 80], [70, 80, 90], [
                 65, 75, 85], [50, 60, 70], [69, 79, 89]])

In [119]:
score

array([[60, 70, 80],
       [70, 80, 90],
       [65, 75, 85],
       [50, 60, 70],
       [69, 79, 89]])

In [120]:
data[0]

'赵大'

In [125]:
data == '张三'

array([False, False,  True, False, False])

In [124]:
data[data == '张三']

array(['张三'], dtype='<U2')

In [126]:
score > 80

array([[False, False, False],
       [False, False,  True],
       [False, False,  True],
       [False, False, False],
       [False, False,  True]])

In [128]:
score[score < 80]

array([60, 70, 70, 65, 75, 50, 60, 70, 69, 79])

# 矢量计算

In [129]:
data1 = np.array([[1, 2, 3], [4, 5, 6]])
data2 = np.array([[1, 2, 3], [4, 5, 6]])

### 大小相同的数组计算

In [130]:
data1

array([[1, 2, 3],
       [4, 5, 6]])

In [131]:
data1+data2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [132]:
data1-data2

array([[0, 0, 0],
       [0, 0, 0]])

In [133]:
data1*data2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [134]:
data1/data2

array([[1., 1., 1.],
       [1., 1., 1.]])

### 广播

In [135]:
data1+5

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [136]:
data1*5

array([[ 5, 10, 15],
       [20, 25, 30]])

In [137]:
data3 = np.array([10, 20, 30])

In [138]:
data3

array([10, 20, 30])

In [139]:
data1+data3

array([[11, 22, 33],
       [14, 25, 36]])

In [143]:
data4 = np.array([[100], [200]])

In [144]:
data4

array([[100],
       [200]])

In [145]:
data1+data4

array([[101, 102, 103],
       [204, 205, 206]])

In [146]:
data1*data4

array([[ 100,  200,  300],
       [ 800, 1000, 1200]])

# 数组的常规操作

In [147]:
data = np.arange(0, 16).reshape((4, 4))

In [148]:
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

## 数组的迭代

In [152]:
for i in data.flat: # 数组的一个迭代器
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


In [151]:
for i in data:
    for j in i:
        print(j)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


## 数组展开

In [154]:
data.reshape(-1) # 使用reshape(-1)将数组转为一维

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [156]:
data.flatten() # 将数组转为一维

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [157]:
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [161]:
data.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

## 数组转置

In [162]:
data.T

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In [163]:
data.transpose()

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

## 数组滚动

In [170]:
data = np.arange(27).reshape(3, 3, 3)

In [171]:
data

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [172]:
data.T

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

In [177]:
np.rollaxis(data, 0)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [178]:
np.rollaxis(data, 1)

array([[[ 0,  1,  2],
        [ 9, 10, 11],
        [18, 19, 20]],

       [[ 3,  4,  5],
        [12, 13, 14],
        [21, 22, 23]],

       [[ 6,  7,  8],
        [15, 16, 17],
        [24, 25, 26]]])

In [179]:
np.rollaxis(data, 2)

array([[[ 0,  3,  6],
        [ 9, 12, 15],
        [18, 21, 24]],

       [[ 1,  4,  7],
        [10, 13, 16],
        [19, 22, 25]],

       [[ 2,  5,  8],
        [11, 14, 17],
        [20, 23, 26]]])

In [180]:
np.rollaxis(data, 2, 1)

array([[[ 0,  3,  6],
        [ 1,  4,  7],
        [ 2,  5,  8]],

       [[ 9, 12, 15],
        [10, 13, 16],
        [11, 14, 17]],

       [[18, 21, 24],
        [19, 22, 25],
        [20, 23, 26]]])

## 交换数组的轴

数组的维度叫做(axes)，轴的个数叫做秩(rank)，axes0就是横轴，axes1叫做纵轴

In [187]:
data = np.arange(27).reshape(3, 3, 3)

In [190]:
data.ndim

3

In [188]:
data

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [189]:
np.swapaxes(data, 2, 0)

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

## 添加数组元素

### 数组以行进行拼接

In [192]:
data = np.arange(12)

In [193]:
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [194]:
np.concatenate((data, np.array([12])))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [195]:
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [196]:
data1 = np.array([12, 13])

In [197]:
data1

array([12, 13])

In [198]:
np.concatenate((data, data1))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [206]:
data1 = np.arange(6)
data2 = np.arange(8, 14)

In [207]:
np.hstack((data1, data2))

array([ 0,  1,  2,  3,  4,  5,  8,  9, 10, 11, 12, 13])

### 以列进行拼接

In [200]:
data1 = np.arange(6)
data2 = np.arange(8, 14)

In [201]:
data1

array([0, 1, 2, 3, 4, 5])

In [202]:
data2

array([ 8,  9, 10, 11, 12, 13])

In [205]:
np.vstack((data1, data2))

array([[ 0,  1,  2,  3,  4,  5],
       [ 8,  9, 10, 11, 12, 13]])